version: "3.8"

services:
  utareco-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount source code for development
      - ./app:/app/app
      - ./tests:/app/tests
      # Mount audio files directory
      - ./audio_files:/app/audio_files
      # Mount database directory
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///app/data/utareco.db
      - AUDIO_FILES_DIR=/app/audio_files
      - DEBUG=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  utareco-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - ./audio_files:/app/audio_files
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///app/data/utareco_dev.db
      - AUDIO_FILES_DIR=/app/audio_files
      - DEBUG=true
    command:
      [
        "uv",
        "run",
        "--frozen",
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    profiles:
      - dev

volumes:
  audio_files:
  data:
